apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}
type: Opaque
data:
  {{- if .Values.secret }}
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
